# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_comment',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename_hash',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
